package Clases;

import javax.swing.JTextArea;

public class ListarMultas extends javax.swing.JPanel {
    private Multa[] multas;

    /**
     * Creates new form ListarMultas
     */
    public ListarMultas(Multa[] multas) {
        initComponents();
        mostrarMultas();
        this.multas = multas; 
        if (multas != null && multas.length > 0) {
            StringBuilder multasInfo = new StringBuilder();
            for (Multa multa : multas) {
                multasInfo.append("Código: ").append(multa.getCodigo()).append(" - ")
                        .append("Nombre: ").append(multa.getNombre()).append(" - ")
                        .append("Tipo: ").append(multa.getTipo()).append("\n");
            }
            multasListadas.setText(multasInfo.toString());
        } else {
            multasListadas.setText("No hay multas para mostrar.");
        }
    }
    
    private void mostrarMultas() {
        if (multas != null && multas.length > 0) {
            StringBuilder multasInfo = new StringBuilder();
            for (Multa multa : multas) {
                multasInfo.append("Código: ").append(multa.getCodigo()).append(" - ")
                        .append("Nombre: ").append(multa.getNombre()).append(" - ")
                        .append("Tipo: ").append(multa.getTipo()).append("\n");
            }
            multasListadas.setText(multasInfo.toString());
        } else {
            multasListadas.setText("No hay multas para mostrar.");
        }
    }
    
    public JTextArea getMultasListadas() {
    return multasListadas;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        multasListadas = new javax.swing.JTextArea();

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel4.setText("Lista de Multas");

        multasListadas.setColumns(20);
        multasListadas.setRows(5);
        jScrollPane1.setViewportView(multasListadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea multasListadas;
    // End of variables declaration//GEN-END:variables
}
